application: rashmi-choube
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /ebikeindia
  script: ebikeindia.py

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
